const assert=require('node:assert/strict');
const M=require('../dist/modulation.js');
const signal=new Float32Array(48);
for(let i=0;i<48;i++)if(M.frequency(i)<250)signal[i]=.8;
const bass=M.create('bass','blobs'),treble=M.create('high','peaks');
let out=M.step([bass,treble],signal,1,[]);
assert(out.blobs>.7);assert.equal(out.peaks,0);assert(!('particles' in out));
assert.equal(M.step([{...bass,enabled:false}],signal,1,[]).blobs,0);
assert.equal(M.step([{...bass,threshold:.9}],signal,1,[]).blobs,0);
const narrow={...bass,source:'custom',low:1000,high:1001};
assert.equal(M.step([narrow],signal,1,[]).blobs,0);
const sparse=new Float32Array(48);sparse[4]=1;
assert(M.step([{...bass,response:'peak'}],sparse,1,[]).blobs>M.step([bass],sparse,1,[]).blobs);
function decay(fps){const states=[{value:1}];for(let i=0;i<fps;i++)M.step([bass],new Float32Array(48),1/fps,states);return states[0].value;}
assert(Math.abs(decay(30)-decay(120))<1e-10);
assert.throws(()=>M.validate([{...bass,low:2000,high:1000}]));
assert.throws(()=>M.validate([{...bass,amount:NaN}]));
assert.throws(()=>M.validate(Array(13).fill(bass)));
assert.throws(()=>M.validate([{...bass,target:'unknown'}]));
assert.deepEqual(M.validate(JSON.parse(JSON.stringify([bass,treble]))),[bass,treble]);
console.log('PASS: band isolation, disable, threshold, narrow ranges, peak response, frame-independent release, validation and JSON round trip.');
// Quiet signals remain useful, loud ones stay bounded, and silence never opens the gate.
const shape=new Float32Array(48);shape[4]=.8;shape[5]=.4;
const soft=M.condition(shape.map(v=>v*.1),.004,-60,1.5);
const loud=M.condition(shape,.3,-60,1.5);
assert(soft.active&&loud.active);assert(soft.bands[4]>.5);
assert(Math.abs(soft.bands[4]-loud.bands[4])<1e-6);
assert(!M.condition(shape,0,-90,5).active);
assert(!M.condition(shape,.00001,-60,5).active);
assert.equal(M.advance(12,1,false,3,3),12);
assert.equal(M.advance(12,1,true,0,3),12);
assert(M.advance(12,1,true,.1,1)>12);
const intensityRoute={...bass,target:'intensity'};
assert(M.step([intensityRoute],signal,1,[]).intensity>.7);
const beatRoute={...bass,source:'beat',target:'peaks'};
assert(M.step([beatRoute],new Float32Array(48),1,[],{beat:.8}).peaks>.7);
assert.equal(M.step([beatRoute],signal,1,[],{beat:0}).peaks,0);
assert(M.read('bass',signal)>.7);
assert.equal(M.read('impact',signal,{impact:.62}),.62);
assert.equal(M.read('none',signal,{impact:1}),0);
console.log('PASS: quiet/loud normalization, silence gate, motion only from an active pairing.');
